development: &default
  adapter: postgresql
  min_messages: WARNING
  host: localhost
  encoding: unicode
  database: EXPENSES_development
  username: postgres
  password: "12345"
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: EXPENSES_test<%= ENV['TEST_ENV_NUMBER'] %>

production:
  adapter: "postgresql"
  min_messages: "WARNING"
  host: "localhost"
  encoding: "unicode"
  username: postgres
  password: "Bild3Quak!"
  database: "EXPENSES_production"
  pool: 5
  timeout: 5000